import type { LandmarkGroup } from '../prefs';

/** Generated by scripts/landmarks.ts into landmarks.json. */
export interface Landmark {
  id: string;
  name: string;
  kind: string;
  lat: number;
  lng: number;
  /** Distance along the route from the start, km. */
  km: number;
}

export function landmarkGroup(kind: string): LandmarkGroup {
  if (kind === 'city' || kind === 'town' || kind === 'village') return 'towns';
  if (kind === 'fuel') return 'fuel';
  return 'services';
}

export function landmarkLabel(kind: string): string {
  return (
    {
      city: 'City',
      town: 'Town',
      village: 'Village',
      fuel: 'Fuel station',
      hospital: 'Hospital',
      police: 'Police',
      atm: 'ATM',
      bank: 'Bank',
      supermarket: 'Shop',
      border_control: 'Border post',
    }[kind] ?? kind
  );
}
